version: '3.4'

services:
  nestbot:
    image: nestbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3900:3900
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
